# -*- coding: utf-8 -*-
"""bmi_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bph03wGoLdOtos_a_Oktx01rsJCY5JJr
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from pathlib import Path

st.set_page_config(page_title="BMI App", page_icon="💪")

DATA_FILE = "bmi_data.csv"

def load_data():
    path = Path(DATA_FILE)
    if path.exists():
        return pd.read_csv(path)
    else:
        cols = ["time", "name", "age", "gender", "height", "weight", "bmi", "category"]
        return pd.DataFrame(columns=cols)

def save_entry(name, age, gender, height, weight, bmi, category):
    df = load_data()
    new_row = {
        "time": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "name": name,
        "age": age,
        "gender": gender,
        "height": height,
        "weight": weight,
        "bmi": round(bmi, 2),
        "category": category
    }
    df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    df.to_csv(DATA_FILE, index=False)

def calculate_bmi(height, weight):
    h = height / 100
    return weight / (h * h)

def bmi_category(bmi):
    if bmi < 18.5:
        return "Under-weight"
    elif bmi < 25:
        return "Normal"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

def suggestions(category):
    plans = {
        "Under-weight": (
            ["Eat more frequently", "Add nuts, milk, eggs", "Increase carbs"],
            ["Light strength training", "Walking"]
        ),
        "Normal": (
            ["Balanced meals", "Fruits & vegetables", "Drink water"],
            ["Brisk walking", "Yoga"]
        ),
        "Overweight": (
            ["Reduce sugar", "More fiber", "Avoid fried food"],
            ["Daily walking", "Light workouts"]
        ),
        "Obese": (
            ["Avoid sugar", "Smaller portions", "More vegetables"],
            ["Slow walking", "Stretching"]
        )
    }
    return plans[category]

st.title("💪 BMI Calculator App")

with st.form("form"):
    name = st.text_input("Name")
    age = st.number_input("Age", 1, 120)
    gender = st.selectbox("Gender", ["Male", "Female", "Other"])
    height = st.number_input("Height (cm)", 100.0, 250.0)
    weight = st.number_input("Weight (kg)", 20.0, 200.0)
    submit = st.form_submit_button("Calculate BMI")

if submit:
    bmi = calculate_bmi(height, weight)
    category = bmi_category(bmi)
    save_entry(name, age, gender, height, weight, bmi, category)

    st.success(f"Your BMI is {bmi:.2f}")
    st.info(f"Category: {category}")

    meals, exercise = suggestions(category)

    st.subheader("🍽 Meal Plan")
    for m in meals:
        st.write("-", m)

    st.subheader("🏃 Exercise")
    for e in exercise:
        st.write("-", e)

st.subheader("📊 Saved Records")
st.dataframe(load_data())

!streamlit run bmi_app.py &> /dev/null &

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb
!cloudflared tunnel --url http://localhost:8501